config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: 'admin/sessions', registrations: 'admin/registrations'}
  devise_scope :admin do
    get 'delta', to: 'admin/sessions#delta'
    get 'admins/sign_in', to: 'admin/sessions#delta'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users"}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  root 'welcome#index'
  get '/ref/:referrer' => 'welcome#index'

  # get '/portfolio/new' => 'portfolio_accounts#new'
  # post '/portfolio' => 'portfolio_accounts#create'
  resources :portfolio, controller: 'portfolio_accounts'
  get '/target/new' => 'target_accounts#new'
  post '/target' => 'target_accounts#create'

  resources :companies
  get '/profile' => 'users#profile'
  put '/profile' => 'users#update'
  patch '/profile' => 'users#update'
  get '/profile/new' => 'users#new_profile'
  post '/profile' => 'users#create_profile'
  patch '/submit' => 'users#submit_application'
  get '/submitted' => 'users#submitted'
  get '/edit/password/:id' => 'users#edit_password', as: :edit_password
  patch '/edit/password/:id' => 'users#update_password', as: :update_password

  resources :members, only: [:index, :show, :update]

  resources :connections

  resources :requests, only: [:index, :create]
  resources :comments
  resources :member_requests, only: [:index, :create]
  resources :app_images, only: [:new, :create]

  namespace :admin do
    resources :applications, only: [:index, :show, :update]
    resources :members, only: [:index, :show, :new, :create]
    resources :member_requests, only: [:index, :destroy]
    resources :industries, only: [:new, :create]
    resources :departments, only: [:new, :create]
    get '/new_requests' => 'members#new_requests'
    get '/unapproved' => 'members#unapproved'
    get '/rejected' => 'members#rejected'
    get '/current' => 'members#current'
    get '/new_companies' => 'companies#index'
    put '/members/suspend_member/:id' => 'members#suspend_member', as: :suspend_member
    patch '/members/suspend_member/:id' => 'members#suspend_member'
    put '/members/approve_member/:id' => 'members#approve_member', as: :approve_member
    patch '/members/approve_member/:id' => 'members#approve_member'
    put '/members/disapprove_member/:id' => 'members#disapprove_member', as: :disapprove_member
    put '/members/disapprove_member/:id' => 'members#disapprove_member'
  end

  resources :inbox, controller: 'conversations', except: [:edit, :show, :update]
  get '/inbox/sent_conversations' => 'conversations#sent'
  get '/inbox/archived_conversations' => 'conversations#archived'
  get '/inbox/trashed_conversations' => 'conversations#trashed'
  match '/inbox/archive_conversations' => 'conversations#archive', via: [:put, :patch]
  match '/inbox/trash_conversations' => 'conversations#trash', via: [:put, :patch]
  get '/inbox/message/:id' => 'conversations#show', as: :inbox_message
  get '/inbox/reply/:id' => 'conversations#reply', as: :inbox_reply
  post '/inbox/reply/:id' => 'messages#create'
  post '/send_message/:id' => 'conversations#send_message'
  resources :messages, only: [:create]
  resources :notifications, only: [:index, :destroy]

  namespace :api do
    namespace :v1 do
      resources :companies, only: [:index]
      get '/company_search' => 'companies#search'
      get '/async_search' => 'companies#async_search'
      get '/company_city_search' => 'companies#city_search'
      get '/member_search' => 'members#search'
      get 'member_city_search' => 'members#city_search'
      get '/company_members/:id' => 'members#company_members'
      get '/company_members_search/:id' => 'members#company_members_search'
      get '/peers' => 'members#peers_search'
      get '/company_peers/:id' => 'members#company_peers_search'
      resources :comments, only: [:index]
      resources :departments, only: [:index]
      resources :industries, only: [:index, :show]
      resources :users, only: [:index, :update]
      get '/user_industries' => 'users#industries'
      patch '/user_industries' => 'users#update_industries'
      get '/user_departments' => 'users#departments'
      patch '/user_departments' => 'users#update_departments'
      get '/current_user' => 'users#user'
      resources :portfolio_industries, only: [:index]
      resources :portfolio_departments, only: [:index]
      resources :conversations, only: [:index]
      get '/sent_conversations' => 'conversations#sent'
      get '/received_conversations' => 'conversations#received'
      get '/archived_conversations' => 'conversations#archived'
      get '/trashed_conversations' => 'conversations#trashed'
      match '/archive_conversations' => 'conversations#archive', via: [:put, :patch]
      match '/trash_conversations' => 'conversations#trash', via: [:put, :patch]
      resources :contact_levels, only: [:index]
      resources :connections, only: [:index, :create]
      resources :messages, only: [:show]
      get '/recipients' => 'connections#recipients'
      get '/recipients/:id' => 'connections#recipient'
      resources :notifications
      resources :referrals, only: [:create, :index]
      get '/avatars' => 'users#avatars'
      get '/states' => 'users#states'
    end
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  has_many :messages, -> {order(created_at: :desc)}, dependent: :destroy
  has_many :sent_conversations, -> {order(created_at: :desc)}, dependent: :destroy
  has_many :received_conversations, -> {order(created_at: :desc)}, dependent: :destroy
  validates :subject, presence: true
  
  def receivers
    received_conversations.map(&:receiver)
  end
  
  def senders
    sent_conversations.map(&:sender)
  end
  
  def participants(user)
    participants = receivers + senders
    participants.uniq.reject{|participant| participant == user}
  end
  
  def read_conversation(user)
    received_convo = received_conversations.find{|rc| rc.receiver == user}
    received_convo.update(opened: true) unless received_convo.nil? || received_convo.opened
  end
end

app/controllers/api/v1/conversations_controller.rb
require 'will_paginate/array'
module Api
  module V1
    class ConversationsController < ApplicationController
      def index
        @sent_conversations = current_user.sent_conversations.paginate(per_page: 5, page: params[:page])
        @received_conversations = current_user.received_conversations.paginate(per_page: 5, page: params[:page])
        @archived_conversations = current_user.archived_conversations.paginate(per_page: 5, page: params[:page])
        @trashed_conversations = current_user.trashed_conversations.paginate(per_page: 5, page: params[:page])
      end

      def sent
        @sent = current_user.conversations_sent.paginate(per_page: 5, page: params[:page])
      end

      def received
        @received = current_user.active_conversations_received.paginate(per_page: 5, page: params[:page])
      end

      def archived
        @archived = current_user.archived_conversations.uniq.paginate(per_page: 5, page: params[:page])
      end

      def trashed
        @trashed = current_user.trashed_conversations.uniq.paginate(per_page: 5, page: params[:page])
      end

      def archive
        conversation_ids = params[:conversation_ids].gsub("[", "").gsub("]", "").split(",")
        begin
          archive_conversations(conversation_ids)
          flash[:success] = "Message(s) archived"
          render json: "wahoo!".to_json
        rescue
          render json: "Oops! Try archiving again".to_json, status: :unprocessable_entity
        end
      end
      
      def archive_conversations(conversation_ids)
        ReceivedConversation.where(conversation_id: conversation_ids).update_all(archived: true, trashed: false) &&
        SentConversation.where(conversation_id: conversation_ids).update_all(archived: true, trashed: false)
      end

      def trash
        conversation_ids = params[:conversation_ids].gsub("[", "").gsub("]", "").split(",")
        begin
          trash_conversations(conversation_ids)
          flash[:success] = "Message(s) trashed"
          render json: "".to_json
        rescue
          render json: "Oops! Try trashing again".to_json, status: :unprocessable_entity
        end
      end
      
      def trash_conversations(conversation_ids)
        ReceivedConversation.where(conversation_id: conversation_ids).update_all(archived: false, trashed: true) &&
        SentConversation.where(conversation_id: conversation_ids).update_all(archived: false, trashed: true)
      end
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :approved_user, :redirect_if_admin

  def index
  end

  def new
  end

  def sent
  end

  def archived
  end

  def trashed
  end

  def new_message
    @recipient = User.find(params[:id])
  end

  def show
    @conversation = Conversation.find(params[:id])
    @conversation.read_conversation(current_user)
    read_notification(params[:note_id]) if params[:read]
  end

  def reply
    @conversation = Conversation.find(params[:id])
  end

  def create
    receiver_ids = params[:ids]
    conversation = Conversation.new(subject: params[:subject])
    if SendMessage.new(params[:subject], params[:body], receiver_ids, current_user).start_conversation
      render json: "Your message was sent!".to_json
    else
      render json: "Couldn't send your message. Please try again".to_json, status: :unprocessable_entity
    end
  end

  def send_message
    member = User.find(params[:id])
    if SendMessage.new(params[:subject], params[:body], [member.id], current_user, member).start_conversation
      render json: "Your message was sent!".to_json
    else
      render json: "Be sure you have a Subject and body filled in.".to_json, status: :unprocessable_entity
    end
  end

  def conversation_params
    params.require(:conversation).permit(:subject)
  end

end

app/views/conversations/_alerts.html.erb
<ul class="list-inline list-unstyled" style="margin-top: 10px;">
  <li ng-click="archiveMessages()" class="pointer"><i class="glyphicon glyphicon-folder-open"></i> Archive</li>
  <li ng-click="trashMessages()" class="pointer"><i class="glyphicon glyphicon-trash"></i> Trash</li>
</ul>

<% flash.each do |name, message| %>
<div class="alert row alert-<%= name %>" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= message %>
</div>
<% end %>
<div ng-if="messageError" class="alert row alert-danger">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  {{messageError}}
</div>

app/views/conversations/_conversation_form.html.erb
<form name="new_conversation" class="form-horizontal" ng-submit="startConversation(conversation)">

  <input type="hidden" name="name" ng-value="conversation.receiver_id = <%= sender_id %>">
  <div class="form-group">
    <input ng-model="conversation.subject" type="text" name="name" value="" class="form-control" placeholder="subject">
  </div>

  <div class="form-group">
    <textarea ng-model="conversation.body" name="body" rows="8" cols="40" class="form-control" placeholder="Body message"></textarea>
  </div>

  <div class="form-group pull-right">
    <input type="submit" name="name" value="Send" class="btn btn-default">
    <input type="button" name="name" value="Cancel" class="btn btn-default">
  </div>

</form>

app/views/conversations/_menu.html.erb
  <div class="col-lg-2">
    <h4><i class="fa fa-envelope blue"></i> Messages</h4>
    <a href="<%= new_inbox_path %>" class="message-button col-lg-12 text-center"><i class="fa fa-pencil-square-o"></i> New Message</a>
    <ul class="list-unstyled inbox-list">
      <a href="<%= inbox_index_path %>"><li ng-class="{blue: totalReceivedPages}"><i class="glyphicon glyphicon-arrow-down"></i> Inbox</li></a>
      <a href="<%= inbox_sent_conversations_path %>"><li ng-class="{blue: totalSentPages}"><i class="glyphicon glyphicon-arrow-up"></i> Sent</li></a>
      <a href="<%= inbox_archived_conversations_path %>"><li ng-class="{blue: totalArchivedPages}"><i class="glyphicon glyphicon-folder-open"></i> Archived</li></a>
      <a href="<%= inbox_trashed_conversations_path %>"><li ng-class="{blue: totalTrashedPages}"><i class="glyphicon glyphicon-trash"></i> Trash</li></a>
    </ul>
  </div>

app/views/conversations/_message_form.html.erb
<form name="new_conversation" class="form-horizontal" ng-submit="sendMessage(message)">

  <input type="hidden" name="name" ng-value="message.conversation_id = <%= conversation_id %>">
  <input type="hidden" name="name" ng-value="message.receiver_id = <%= receiver_id %>">

  <div class="form-group">
    <textarea ng-model="message.body" name="body" rows="8" cols="40" class="form-control" placeholder="Body message"></textarea>
  </div>

  <div class="form-group pull-right">
    <input type="submit" name="name" value="Send" class="btn btn-default">
    <input type="button" name="name" value="Cancel" class="btn btn-default">
  </div>

</form>

app/views/conversations/archived.html.erb
<div class="row" ng-controller="ConversationsController">
<div ng-init="getArchivedConversations(1)"></div>
  <%= render 'menu' %>
  <div class="col-lg-9">
    <%= render 'alerts' %>
    
    <div class="message-row-read row" ng-repeat="convo in archivedConversations">
      <ul class="list-unstyled list-inline" ng-repeat="receiver in convo.receivers | limitTo: 1 track by receiver.photo">
        <li><input type="checkbox" name="name" value="" ng-change="addIds(checked, convo.id)" ng-model="checked"></li>
        <li><img ng-src="{{receiver.photo}}" class="linkedin-photo" height="40" width="40" alt="" /></li>
      </ul>
      <a ng-href="/inbox/message/{{convo.id}}"><div class="col-lg-10">
        <p><strong>{{convo.receiver_names | cut:true:30:'...'}}</strong> </p>
        <p>{{convo.message.body | cut:true:100:'...'}}</p>
      </div></a>
    </div>

    <div class="paginate text-center" ng-if="totalArchivedPages > 1">
      <ul class="list-inline list-unstyled">
        <li ng-click="prevPage(totalArchivedPages)"><i class="glyphicon glyphicon-chevron-left"></i></li>
        <li><p> Page {{page}} of {{totalArchivedPages}} </p></li>
        <li ng-click="nextPage(totalArchivedPages)"><i class="glyphicon glyphicon-chevron-right"></i></li>
      </ul>
    </div>
  </div>
</div>

app/views/conversations/index.html.erb
<div class="row" ng-controller="ConversationsController">
<div ng-init="getReceivedConversations(1)"></div>
<%= render 'menu' %>
  <div class="col-lg-9" ng-cloak>
    <%= render 'alerts' %>

    <div class="row" ng-repeat="convo in receivedMessages" ng-class="{'message-row-read': convo.opened, 'message-row-unread': !convo.opened}">
      <ul class="list-unstyled list-inline" ng-repeat="sender in convo.senders | limitTo: 1">
        <li><input type="checkbox" name="name" value="" ng-change="addIds(checked, convo.id)" ng-model="checked"></li>
        <li><img ng-src="{{sender.linkedin_photo}}" class="linkedin-photo" height="40" width="40" alt="" /></li>
      </ul>
      <a ng-href="/inbox/message/{{convo.id}}">
        <div class="col-lg-10">
          <p><strong>{{convo.sender_names | cut:true:100:'...'}}</strong></p>
          <span><p>{{convo.message.body | cut:true:100:'...'}}</p></span>
        </div>
      </a>
    </div>

    <div class="paginate text-center" ng-if="totalReceivedPages > 1">
      <ul class="list-inline list-unstyled">
        <li ng-click="prevPage(totalReceivedPages)"><i class="glyphicon glyphicon-chevron-left"></i></li>
        <li><p> Page {{page}} of {{totalReceivedPages}} </p></li>
        <li ng-click="nextPage(totalReceivedPages)"><i class="glyphicon glyphicon-chevron-right"></i></li>
      </ul>
    </div>
  </div>
</div>

app/views/conversations/new.html.erb
<div class="row" ng-controller="ConversationsController">
  <%= render 'menu' %>
  
  <div class="col-lg-9">
    </br>
    </br>
    <div ng-if="successMessage" class="alert alert-success row">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{successMessage}}
    </div>
    <div ng-if="errorMessage" class="alert alert-danger row">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{errorMessage}}
    </div>
    <form name="new_conversation" class="form-horizontal" ng-submit="startConversation(conversation)">

      <div class="outer-send-message row">
        <table>
          <tr>
            <th ng-repeat="recipient in recipients"><img ng-src="{{recipient.photo}}" class="linkedin-photo" style="margin-right: 5px;" width="20" height="20" alt="" />{{recipient.name}}<i style="margin-left: 10px;" class="fa fa-times" ng-click="removeRecipient(recipient)"></i></th>
            <th class="to-message-box">
              <input type="text" name="name" value="" ng-model="selectedRecipient" id="load-recipients" typeahead-loading='loadingRecipients' typeahead-select-on-blur="true" uib-typeahead="recipient.name for recipient in getConnections($viewValue) | limitTo: 8" typeahead-on-select="addRecipient($item);selectedRecipient = null;" placeholder="Type a name" autocomplete="off">
            </th>
          </tr>
        </table>
      </div>
      
      <div class="row message-area">
        <input ng-model="conversation.subject" type="text" name="name" value="" class="col-lg-12" placeholder="subject">
      
        <input type="hidden" name="name" ng-value="">
        <textarea ng-model="conversation.body" name="body" rows="8" cols="40" class="col-lg-12" placeholder="Body message"></textarea>

      </div>
      <div class="row pull-left message-buttons">
        <input type="submit" name="name" value="Send" class="btn btn-default">
        <input type="button" name="name" value="Cancel" class="btn btn-default">
      </div>

    </form>
  </div>
</div>

app/views/conversations/new_message.html.erb
<div ng-controller="ConversationsController">
  <div class="row">
    <p> Send a message to: </p>
    <h5><%= @recipient.full_name %></h5>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="alert alert-success" ng-cloak ng-if="conversationSuccessful">
        <h4>{{response}}</h4>
      </div>
      <div class="alert alert-danger" ng-cloak ng-if="conversationError">
        <p> Please fix the following problems: </p>
        <ul ng-repeat="response in responses">
          <li>{{response}}</li>
        </ul>
      </div>
      <%= render partial: 'conversation_form', locals: {sender_id: @recipient.id} %>
    </div>
  </div>
</div>

app/views/conversations/reply.html.erb
<div class="row" ng-controller="ConversationsController">
<%= render 'menu' %>
  <div class="col-lg-9" ng-cloak>
    <br>
    <br>
    <form name="reply-form" ng-submit="postReply(reply)">
      <div class="outer-send-message row">
        <table>
          <tr>
            <th ng-repeat="recipient in recipients"><img ng-src="{{recipient.linkedin_photo}}" class="linkedin-photo" style="margin-right: 5px;" width="20" height="20" alt="" />{{recipient.full_name}}<i style="margin-left: 10px;" class="fa fa-times"></i></th>
            <th class="to-message-box">
              <input type="text" name="name" value="" ng-model="selectedRecipient" id="load-recipients" typeahead-loading='loadingRecipients' typeahead-select-on-blur="true" uib-typeahead="recipient.full_name for recipient in getConnections($viewValue) | limitTo: 8" typeahead-on-select="addRecipient($item);selectedRecipient = null;" placeholder="Type a name" autocomplete="off">
            </th>
          </tr>
        </table>
      </div>
    
      <div class="message-area row">
        <input type="hidden" value="<%= @conversation.id %>" ng-value="reply.message_id = <%= @conversation.id %>" name="name" value="">
        <input type="hidden" value="<%= @conversation.sender.id %>" id="send-to" name="name" value="">
        <input value="Re: <%= @conversation.subject %>" type="text" name="name" class="col-lg-12" placeholder="subject">
        <div>
          <div class="col-lg-12">
            <textarea name="name" class="col-lg-12 row reply-textarea" ng-model="reply.body"></textarea>
          </div>
          <% @conversation.messages.each do |message| %>
            <div class="col-lg-12">
              <p><%= message.created_at.strftime("%b %e, %l:%M %p") + " - " + message.sender.full_name %> </p>
              <p>---------------------------------------------------------------</p>
              <p><%= message.body %></p>
            </div>
          <% end %>
            <div class="col-lg-12">
              <p><%= @conversation.created_at.strftime("%b %e, %l:%M %p") + " - " + @conversation.sender.full_name %></p>
              <p>---------------------------------------------------------------</p>
              <p><%= @conversation.body %></p>
            </div>
        </div>
      </div>
      <div class="row pull-left message-buttons">
        <input type="submit" name="name" value="Send" class="btn btn-default">
        <input type="button" name="name" value="Cancel" class="btn btn-default">
      </div>
    </form>
  </div>
</div>

app/views/conversations/sent.html.erb
<div class="row" ng-controller="ConversationsController">
<div ng-init="getSentConversations(1)"></div>
  <%= render 'menu' %>
  <div class="col-lg-9">
    <%= render 'alerts' %>
    
    <div class="message-row-read row" ng-repeat="convo in sentMessages">
      <ul class="list-unstyled list-inline" ng-repeat="receiver in convo.receivers | limitTo: 1">
        <li><input type="checkbox" name="name" value="" ng-change="addIds(checked, convo.id)" ng-model="checked"></li>
        <li><img ng-src="{{receiver.linkedin_photo}}" class="linkedin-photo" height="40" width="40" alt="" /></li>
      </ul>
      <a ng-href="/inbox/message/{{convo.id}}">
        <div class="col-lg-10">
          <p><strong>{{convo.receiver_names | cut:true:30:'...'}}</strong></p>
          <p>{{convo.message.body | cut:true:100:'...'}}</p>
        </div>
      </a>
    </div>
    
    <div class="paginate text-center" ng-if="totalSentPages > 1">
      <ul class="list-inline list-unstyled">
        <li ng-click="prevPage(totalSentPages)"><i class="glyphicon glyphicon-chevron-left"></i></li>
        <li><p> Page {{page}} of {{totalSentPages}} </p></li>
        <li ng-click="nextPage(totalSentPages)"><i class="glyphicon glyphicon-chevron-right"></i></li>
      </ul>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="row" ng-controller="MessagesController as msgs" ng-init="msgs.getMessages(<%= params[:id] %>)">
<%= render 'menu' %>
  <div class="col-lg-9" ng-cloak>
    <ul class="list-inline list-unstyled" style="margin-top: 10px;">
      <li ng-click="archiveMessage(<%= @conversation.id %>)" class="pointer"><i class="glyphicon glyphicon-folder-open"></i> Archive</li>
      <li ng-click="trashMessage(<%= @conversation.id %>)" class="pointer"><i class="glyphicon glyphicon-trash"></i> Trash</li>
    </ul>

    <div ng-if="msgs.messageSuccess" class="alert row alert-success" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{msgs.messageSuccess}}
    </div>
    <div ng-if="msgs.messageError" class="alert row alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{msgs.messageError}}
    </div>
    
    <div class="message-row-read row">
      Subject: {{msgs.conversation.subject}}
    </div>
    
    <div class="reply-div row" ng-if="!msgs.showReplyBox">
      <a href="#" ng-click="msgs.showReply()">Reply</a>
    </div>
    
    <div class="reply-textarea row" ng-if="msgs.showReplyBox">
      <form ng-submit="msgs.sendReplyMessage(message)">
        <div class="outer-send-message" style="margin-bottom: 1px;">
          <table>
            <tr>
              <th ng-repeat="receiver in msgs.receivers"><img ng-src="{{receiver.photo}}" class="linkedin-photo" style="margin-right: 5px;" height="20" width="20" alt="" />{{receiver.name}}<i style="margin-left: 10px;" class="fa fa-times" ng-click="msgs.removeReceiver(receiver)"></i></th>
              <th class="to-message-box">
                <input type="text" name="name" value="" ng-model="selectedRecipient" id="load-recipients" typeahead-loading='loadingRecipients' typeahead-select-on-blur="true" uib-typeahead="recipient.name for recipient in msgs.getConnections($viewValue) | limitTo: 8" typeahead-on-select="msgs.addReceiver($item);selectedRecipient = null;" placeholder="Type a name" autocomplete="off">
              </th>
            </tr>
          </table>
        </div>
        <textarea name="name" rows="8" cols="40" autofocus="true" rows="8" ng-model="message.body"></textarea>
        <div class="reply-button">
          <input type="submit" name="commit" value="Reply">
          <i ng-click="msgs.discardMessage(message)" class="glyphicon glyphicon-trash pull-right" style="margin-top: 4px; cursor: pointer;"></i>
        </div>
      </form>
    </div>
    
    <div class="message-row-read row" style="cursor: pointer;" ng-repeat="message in msgs.messages" ng-click="msgs.displayMessage(message)">
      <div class="col-lg-1">
        <img ng-src="{{message.sender.photo}}" class="linkedin-photo" height="40" width="40" alt="" />
      </div>
      <div class="col-lg-11">
        <strong><p> {{message.sender.name}} </p></strong>
        <p ng-show="!message.full_message"> {{message.body | cut:true:100:'...'}} </p>
        <p ng-show="message.full_message"> {{message.body}} </p>
      </div>
    </div>
  </div>
</div>

app/views/conversations/trashed.html.erb
<div class="row" ng-controller="ConversationsController">
<div ng-init="getTrashedConversations(1)"></div>
  <%= render 'menu' %>
  <div class="col-lg-9">
    <%= render 'alerts' %>

    <div class="message-row-read row" ng-repeat="convo in trashedConversations">
      <ul class="list-unstyled list-inline" ng-repeat="receiver in convo.receivers | limitTo: 1 track by receiver.photo">
        <li><input type="checkbox" name="name" ng-change="addIds(checked, convo.id)" ng-model="checked"></li>
        <li><img ng-src="{{receiver.photo}}" class="linkedin-photo" height="40" width="40" alt="" /></li>
      </ul>
      <a href="/inbox/message/{{convo.id}}"><div class="col-lg-10">
        <p><strong>{{convo.receiver_names | cut:true:30:'...'}}</strong></p>
        <p>{{convo.message.body | cut:true:100:'...'}}</p>
      </div></a>
    </div>

    <div class="paginate text-center" ng-if="totalTrashedPages > 1">
      <ul class="list-inline list-unstyled">
        <li ng-click="prevPage(totalTrashedPages)"><i class="glyphicon glyphicon-chevron-left"></i></li>
        <li><p> Page {{page}} of {{totalTrashedPages}} </p></li>
        <li ng-click="nextPage(totalTrashedPages)"><i class="glyphicon glyphicon-chevron-right"></i></li>
      </ul>
    </div>
  </div>
</div>