config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: 'admin/sessions', registrations: 'admin/registrations'}
  devise_scope :admin do
    get 'delta', to: 'admin/sessions#delta'
    get 'admins/sign_in', to: 'admin/sessions#delta'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users"}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  root 'welcome#index'
  get '/ref/:referrer' => 'welcome#index'

  # get '/portfolio/new' => 'portfolio_accounts#new'
  # post '/portfolio' => 'portfolio_accounts#create'
  resources :portfolio, controller: 'portfolio_accounts'
  get '/target/new' => 'target_accounts#new'
  post '/target' => 'target_accounts#create'

  resources :companies
  get '/profile' => 'users#profile'
  put '/profile' => 'users#update'
  patch '/profile' => 'users#update'
  get '/profile/new' => 'users#new_profile'
  post '/profile' => 'users#create_profile'
  patch '/submit' => 'users#submit_application'
  get '/submitted' => 'users#submitted'
  get '/edit/password/:id' => 'users#edit_password', as: :edit_password
  patch '/edit/password/:id' => 'users#update_password', as: :update_password

  resources :members, only: [:index, :show, :update]

  resources :connections

  resources :requests, only: [:index, :create]
  resources :comments
  resources :member_requests, only: [:index, :create]
  resources :app_images, only: [:new, :create]

  namespace :admin do
    resources :applications, only: [:index, :show, :update]
    resources :members, only: [:index, :show, :new, :create]
    resources :member_requests, only: [:index, :destroy]
    resources :industries, only: [:new, :create]
    resources :departments, only: [:new, :create]
    get '/new_requests' => 'members#new_requests'
    get '/unapproved' => 'members#unapproved'
    get '/rejected' => 'members#rejected'
    get '/current' => 'members#current'
    get '/new_companies' => 'companies#index'
    put '/members/suspend_member/:id' => 'members#suspend_member', as: :suspend_member
    patch '/members/suspend_member/:id' => 'members#suspend_member'
    put '/members/approve_member/:id' => 'members#approve_member', as: :approve_member
    patch '/members/approve_member/:id' => 'members#approve_member'
    put '/members/disapprove_member/:id' => 'members#disapprove_member', as: :disapprove_member
    put '/members/disapprove_member/:id' => 'members#disapprove_member'
  end

  resources :inbox, controller: 'conversations', except: [:edit, :show, :update]
  get '/inbox/sent_conversations' => 'conversations#sent'
  get '/inbox/archived_conversations' => 'conversations#archived'
  get '/inbox/trashed_conversations' => 'conversations#trashed'
  match '/inbox/archive_conversations' => 'conversations#archive', via: [:put, :patch]
  match '/inbox/trash_conversations' => 'conversations#trash', via: [:put, :patch]
  get '/inbox/message/:id' => 'conversations#show', as: :inbox_message
  get '/inbox/reply/:id' => 'conversations#reply', as: :inbox_reply
  post '/inbox/reply/:id' => 'messages#create'
  post '/send_message/:id' => 'conversations#send_message'
  resources :messages, only: [:create]
  resources :notifications, only: [:index, :destroy]

  namespace :api do
    namespace :v1 do
      resources :companies, only: [:index]
      get '/company_search' => 'companies#search'
      get '/async_search' => 'companies#async_search'
      get '/company_city_search' => 'companies#city_search'
      get '/member_search' => 'members#search'
      get 'member_city_search' => 'members#city_search'
      get '/company_members/:id' => 'members#company_members'
      get '/company_members_search/:id' => 'members#company_members_search'
      get '/peers' => 'members#peers_search'
      get '/company_peers/:id' => 'members#company_peers_search'
      resources :comments, only: [:index]
      resources :departments, only: [:index]
      resources :industries, only: [:index, :show]
      resources :users, only: [:index, :update]
      get '/user_industries' => 'users#industries'
      patch '/user_industries' => 'users#update_industries'
      get '/user_departments' => 'users#departments'
      patch '/user_departments' => 'users#update_departments'
      get '/current_user' => 'users#user'
      resources :portfolio_industries, only: [:index]
      resources :portfolio_departments, only: [:index]
      resources :conversations, only: [:index]
      get '/sent_conversations' => 'conversations#sent'
      get '/received_conversations' => 'conversations#received'
      get '/archived_conversations' => 'conversations#archived'
      get '/trashed_conversations' => 'conversations#trashed'
      match '/archive_conversations' => 'conversations#archive', via: [:put, :patch]
      match '/trash_conversations' => 'conversations#trash', via: [:put, :patch]
      resources :contact_levels, only: [:index]
      resources :connections, only: [:index, :create]
      resources :messages, only: [:show]
      get '/recipients' => 'connections#recipients'
      get '/recipients/:id' => 'connections#recipient'
      resources :notifications
      resources :referrals, only: [:create, :index]
      get '/avatars' => 'users#avatars'
      get '/states' => 'users#states'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user_or_admin
  before_filter :redirect_from_welcome
  layout 'landing_page'

  def index
    if params[:referrer]
      redirect_to user_omniauth_authorize_path(:linkedin, referrer: params[:referrer])
    end
  end

  def redirect_from_welcome
    if user_signed_in?
      redirect_to profile_path
    end
  end

end

app/views/welcome/_forty_five.html.erb
<svg id="svg" viewbox="0 0 100 100" height="180" class="text-center">
  <circle cx="50" cy="50" r="45" fill-opacity="0"/>
    <path fill="none" stroke-linecap="square" stroke-width="4" stroke="#8c9fbd"
      stroke-dasharray="112,500"
      d="M50 10
        a 40 40 0 0 1 0 80
        a 40 40 0 0 1 0 -80"/>
    <path fill="none" stroke-linecap="square" stroke-width="4" stroke="#2c3d59" stroke-dashoffset="-8.35em"
      stroke-dasharray="129,500"
      d="M50 10
        a 40 40 0 0 1 0 80
        a 40 40 0 0 1 0 -80"/>
     <path fill="none" stroke-linecap="round" stroke-width="4" stroke="#42bdff" stroke-dashoffset="-17.8em"
       stroke-dasharray="1,250.2"
       d="M50 10
         a 40 40 0 0 1 0 80
         a 40 40 0 0 1 0 -80"/>
     <path fill="none" stroke-linecap="round" stroke-width="4" stroke="#42bdff" stroke-dashoffset="-8.1em"
       stroke-dasharray="1,250.2"
       d="M50 10
         a 40 40 0 0 1 0 80
         a 40 40 0 0 1 0 -80"/>
  <text fill="#fff" x="50" y="50" text-anchor="middle" dy="7" font-size="15" font-weight="200">45%</text>
</svg>

app/views/welcome/_large_percentages.html.erb
<div class="row text-center" style="margin-bottom: 20px;">
  <div class="col-lg-3 col-md-3">
    <img src="<%= asset_path("landing_page/68.png") %>" alt="">
  </div>
  <div class="col-lg-3 col-md-3">
    <img src="<%= asset_path("landing_page/30.png") %>" alt="">
  </div>
  <div class="col-lg-3 col-md-3">
    <img src="<%= asset_path("landing_page/108.png") %>" alt="">
  </div>
  <div class="col-lg-3 col-md-3">
    <img src="<%= asset_path("landing_page/45.png") %>" alt="">
  </div>
</div>

<div class="row text-center start-networking-stats">
  <div class="col-lg-3 col-md-3">
    <p>The average sales professional spends 68% of their time prospecting for new business</p>
  </div>
  <div class="col-lg-3 col-md-3">
    <p>Referral leads convert 30% higher than leads generated from other channels</p>
  </div>
  <div class="col-lg-3 col-md-3">
    <p>10.8% of sales professionals who have closed 5 or more deals attributed to leveraging their network</p>
  </div>
  <div class="col-lg-3 col-md-3">
    <p>Sales professionals who leverage their networks generate 45% more opportunities</p>
  </div>
</div>

<div class="row">
  <div class="col-lg-3 col-md-3 text-center">
    <%= render 'sixty_eight' %>
  </div>
  
  <div class="col-lg-3 col-md-3 text-center">
    <%= render 'thirty' %>
  </div>
  
  <div class="col-lg-3 col-md-3 text-center">
    <%= render 'ten_point_eight' %>
  </div>
  
  <div class="col-lg-3 col-md-3 text-center">
    <%= render 'forty_five' %>
  </div>
</div>

<div class="row start-networking-upcase">
  <div class="col-lg-3 col-md-3 text-center">
    <p>Minimize your prospecting efforts by networking with peers who already have a relationship with your target accounts</p>
  </div>
  <div class="col-lg-3 col-md-3 text-center">
    <p>Access valuable member referrals that can drastically accelerate your sales</p>
  </div>
  <div class="col-lg-3 col-md-3 text-center">
    <p>Maximize your network by having a clear line of sight into members' relationships with companies</p>
  </div>
  <div class="col-lg-3 col-md-3 text-center">
    <p>Expand your peer network to identify more opportunities faster</p>
  </div>
</div>

app/views/welcome/_sixty_eight.html.erb
<svg viewbox="0 0 100 100" height="180" class="text-center">
  <circle cx="50" cy="50" r="45" fill-opacity="0"/>
    <path fill="none" stroke-linecap="square" stroke-width="4" stroke="#8c9fbd"
      stroke-dasharray="170,500"
      d="M50 10
        a 40 40 0 0 1 0 80
        a 40 40 0 0 1 0 -80"/>
     <path fill="none" stroke-linecap="square" stroke-width="4" stroke="#2c3d59" stroke-dashoffset="-12.5em"
      stroke-dasharray="71,500"
      d="M50 10
        a 40 40 0 0 1 0 80
        a 40 40 0 0 1 0 -80"/>
     <path fill="none" stroke-linecap="round" stroke-width="4" stroke="#42bdff" stroke-dashoffset="-17.8em"
       stroke-dasharray="1,250.2"
       d="M50 10
         a 40 40 0 0 1 0 80
         a 40 40 0 0 1 0 -80"/>
     <path fill="none" stroke-linecap="round" stroke-width="4" stroke="#42bdff" stroke-dashoffset="-12.3em"
       stroke-dasharray="1,250.2"
       d="M50 10
         a 40 40 0 0 1 0 80
         a 40 40 0 0 1 0 -80"/>
  <text fill="#fff" x="50" y="50" text-anchor="middle" dy="7" font-size="15" font-weight="200">68%</text>
</svg>

app/views/welcome/_sm_percentages.html.erb
<div class="row text-center">
  
  <div class="row">
    <div class="col-sm-6">
      <img src="<%= asset_path("landing_page/68.png") %>" alt="">
    </div>
    <div class="col-sm-6">
      <img src="<%= asset_path("landing_page/30.png") %>" alt="">
    </div>
  </div>
  
  <div class="sm-start-networking-stats row" style="margin-top: 20px;">
    <div class="col-sm-6">
      <p>The average sales professional spends 68% of their time prospecting for new business</p>
    </div>
    <div class="col-sm-6">
      <p>Referral leads convert 30% higher than leads generated from other channels</p>
    </div>
  </div>
  
  <div class="row" style="margin-top: 20px;">
    <div class="col-sm-6">
      <%= render 'sixty_eight' %>
    </div>
    <div class="col-sm-6">
      <%= render 'thirty' %>
    </div>
  </div>
  
  <div class="row start-networking-upcase">
    <div class="col-sm-6 text-center">
      <p>Minimize your prospecting efforts by networking with peers who already have a relationship with your target accounts</p>
    </div>
    <div class="col-sm-6 text-center">
      <p>Access valuable member referrals that can drastically accelerate your sales</p>
    </div>
  </div>
  
  <div class="row" style="margin-top: 20px;">
    <div class="col-sm-6">
      <img src="<%= asset_path("landing_page/108.png") %>" alt="">
    </div>
    <div class="col-sm-6">
      <img src="<%= asset_path("landing_page/45.png") %>" alt="">
    </div>
  </div>
  
  <div class="row sm-start-networking-stats" style="margin-top: 20px;">
    <div class="col-sm-6">
      <p>10.8% of sales professionals who have closed 5 or more deals attributed to leveraging their network</p>
    </div>
    <div class="col-sm-6">
      <p>Sales professionals who leverage their networks generate 45% more opportunities</p>
    </div>
  </div>
  
  <div class="row" style="margin-top: 20px;">
    <div class="col-sm-6">
      <%= render 'ten_point_eight' %>
    </div>
    <div class="col-sm-6">
      <%= render 'forty_five' %>
    </div>
  </div>
  
  <div class="row start-networking-upcase">
    <div class="col-sm-6 text-center">
      <p>Maximize your network by having a clear line of sight into members' relationships with companies</p>
    </div>
    <div class="col-sm-6 text-center">
      <p>Expand your peer network to identify more opportunities faster</p>
    </div>
  </div>
  
</div>

app/views/welcome/_ten_point_eight.html.erb
<svg id="svg" viewbox="0 0 100 100" height="180" class="text-center">
  <circle cx="50" cy="50" r="45" fill-opacity="0"/>
    <path fill="none" stroke-linecap="square" stroke-width="4" stroke="#8c9fbd"
      stroke-dasharray="27,500"
      d="M50 10
        a 40 40 0 0 1 0 80
        a 40 40 0 0 1 0 -80"/>
     <path fill="none" stroke-linecap="square" stroke-width="4" stroke="#2c3d59" stroke-dashoffset="-2.3em"
      stroke-dasharray="214,500"
      d="M50 10
        a 40 40 0 0 1 0 80
        a 40 40 0 0 1 0 -80"/>
     <path fill="none" stroke-linecap="round" stroke-width="4" stroke="#42bdff" stroke-dashoffset="-17.8em"
       stroke-dasharray="1,250.2"
       d="M50 10
         a 40 40 0 0 1 0 80
         a 40 40 0 0 1 0 -80"/>
     <path fill="none" stroke-linecap="round" stroke-width="4" stroke="#42bdff" stroke-dashoffset="-2em"
       stroke-dasharray="1,250.2"
       d="M50 10
         a 40 40 0 0 1 0 80
         a 40 40 0 0 1 0 -80"/>
  <text fill="#fff" x="50" y="50" text-anchor="middle" dy="7" font-size="15" font-weight="200">10.8%</text>
</svg>

app/views/welcome/_thirty.html.erb
<svg id="svg" viewbox="0 0 100 100" height="180" class="text-center">
  <circle cx="50" cy="50" r="45" fill-opacity="0"/>
    <path fill="none" stroke-linecap="square" stroke-width="4" stroke="#8c9fbd"
      stroke-dasharray="75,500"
      d="M50 10
        a 40 40 0 0 1 0 80
        a 40 40 0 0 1 0 -80"/>
     <path fill="none" stroke-linecap="square" stroke-width="4" stroke="#2c3d59" stroke-dashoffset="-5.7em"
      stroke-dasharray="166,500"
      d="M50 10
        a 40 40 0 0 1 0 80
        a 40 40 0 0 1 0 -80"/>
     <path fill="none" stroke-linecap="round" stroke-width="4" stroke="#42bdff" stroke-dashoffset="-17.8em"
       stroke-dasharray="1,250.2"
       d="M50 10
         a 40 40 0 0 1 0 80
         a 40 40 0 0 1 0 -80"/>
     <path fill="none" stroke-linecap="round" stroke-width="4" stroke="#42bdff" stroke-dashoffset="-5.5em"
       stroke-dasharray="1,250.2"
       d="M50 10
         a 40 40 0 0 1 0 80
         a 40 40 0 0 1 0 -80"/>
  <text fill="#fff" x="50" y="50" text-anchor="middle" dy="7" font-size="15" font-weight="200">30%</text>
</svg>

app/views/welcome/_xs_percentages.html.erb
<div class="row text-center">
  
  <div class="row">
    <div class="col-xs-12">
      <img src="<%= asset_path("landing_page/68.png") %>" alt="">
    </div>
    <div class="col-xs-12 xs-start-networking-stats" style="margin-top: 10px;">
      <p>The average sales professional spends 68% of their time prospecting for new business</p>
    </div>
    <div class="col-xs-12" style="margin-top: 10px;">
      <%= render 'sixty_eight' %>
    </div>
    <div class="col-xs-12 text-center xs-start-networking-upcase">
      <p>Minimize your prospecting efforts by networking with peers who already have a relationship with your target accounts</p>
    </div>
  </div>
  
  <div class="row" style="margin-top: 40px;">
    <div class="col-xs-12">
      <img src="<%= asset_path("landing_page/30.png") %>" alt="">
    </div>
    <div class="col-xs12 xs-start-networking-stats">
      <p>Referral leads convert 30% higher than leads generated from other channels</p>
    </div>
    <div class="col-xs-12" style="margin-top: 10px;">
      <%= render 'thirty' %>
    </div>
    <div class="col-xs-12 text-center xs-start-networking-upcase">
      <p>Access valuable member referrals that can drastically accelerate your sales</p>
    </div>
  </div>
  
  <div class="row" style="margin-top: 30px;">
    <div class="col-xs-12">
      <img src="<%= asset_path("landing_page/108.png") %>" alt="">
    </div>
    <div class="col-xs-12 xs-start-networking-stats">
      <p>10.8% of sales professionals who have closed 5 or more deals attributed to leveraging their network</p>
    </div>
    <div class="col-xs-12" style="margin-top: 10px;">
      <%= render 'ten_point_eight' %>
    </div>
    <div class="col-xs-12 text-center xs-start-networking-upcase">
      <p>Maximize your peer network by having a clear line of sight into members' relationships with companies</p>
    </div>
  </div>
  
  <div class="row" style="margin-top: 30px;">
    <div class="col-xs-12">
      <img src="<%= asset_path("landing_page/45.png") %>" alt="">
    </div>
    <div class="col-xs-12 xs-start-networking-stats">
      <p>Sales professionals who leverage their networks generate 45% more opportunities</p>
    </div>
    <div class="col-xs-12" style="margin-top: 10px;">
      <%= render 'forty_five' %>
    </div>
    <div class="col-xs-12 text-center xs-start-networking-upcase">
      <p>Expand your network to identify more opportunities faster</p>
    </div>
  </div>
  
</div>

app/views/welcome/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,800' rel='stylesheet' type='text/css'>

<div class="front-image">
  <div class="front-image-overlay">
    <div class="container">
      <div class="row front-page-wrapper">
        <img class="pull-left" src="<%= asset_path("logo.png") %>" alt="" />
        <a href="<%= new_user_registration_path %>" class="railway-font request-text-link pull-right">Request Membership</a>
        <a href="<%= login_path %>" class="railway-font pull-right front-sign-in-button black-blue-bordered-button">SIGN IN</a>

        <div class="sales-acceleration">
          <h1 class="questrial-font text-center">Sales Acceleration Network</h1>
          <h4 class="railway-font text-center">Accelerate sales through peer-to-peer networking</h4>
          <a href="<%= user_omniauth_authorize_path(:linkedin) %>" class="railway-font btn margin-for-main-request-button main-request-button">Request Membership</a>
          <div style="margin-bottom: 100px;">
            <h5 class="railway-font text-center">Harness the knowledge of peers to gain access to account insights, contacts and referrals faster.</h5>
            <!-- <a href="" class="railway-font pull-right black-blue-bordered-button">READ OUR STORY</a> -->
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="scroll-acceleration-network scroll-arrow">
    <img src="<%= asset_path('landing_page/scroll-arrow.png') %>" alt="" />
  </div>
</div>

<div class="easy-to-find-and-build">
  <div class="row text-center">
    <h1 class="questrial-font">Easy, Relevant and Productive</h1>
    <h4 class="railway-font gray-text squeeze-text text-center">Easily find and build mutually beneficial business connections with peers who already have established relationships with your target accounts</h4>
  </div>

  <div class="row">

    <div class="col-lg-3 text-center col-lg-offset-1">
      <img src="<%= asset_path("landing_page/briefcase.png") %>" alt="" />
      <h2 class="questrial-font">Search</h2>
      <h5 class="railway-font gray-text squeeze-search-find">Search target companies or departments</h5>
    </div>

    <div class="col-lg-3 text-center lower-find-connect">
      <img src="<%= asset_path("landing_page/briefcase_to_person.png")%>" alt="" />
      <h2 class="text-center questrial-font">Find</h2>
      <h5 class="text-center gray-text squeeze-search-find railway-font">Find peers who already have a relationship with them</h5>
    </div>

    <div class="col-lg-3 lower-find-connect text-center">
      <img src="<%= asset_path("landing_page/circular_people.png") %>" alt="" />
      <h2 class="questrial-font">Connect</h2>
        <h5 class="railway-font gray-text squeeze-search-find">Connect and access insights, contacts and referrals</h5>
    </div>

    <div style="margin-top: 60px;" class="col-sm-12">
      <h4 class="railway-font gray-text text-center">See how PeerNation can help you accelerate sales and eliminate wasteful prospecting </h4>
    </div>
  </div>

  <div class="scroll-easy-to-find scroll-arrow">
    <img src="<%= asset_path('landing_page/scroll-arrow.png') %>" alt="" />
  </div>
</div>

<div class="start-networking">
  <div class="text-center">
    <h1 class="text-center questrial-font">Stop Prospecting and Start Networking with Peers</h1>
    <h4 class="railway-font"> Proven approach that drastically impacts your sales efforts </h4>
  </div>
  
  <div class="container">
    <div class="row">
      
      <div class="hidden-xs hidden-sm">
        <%= render 'large_percentages' %>
      </div>
      
      <div class="hidden-xs hidden-md hidden-lg">
        <%= render 'sm_percentages' %>
      </div>
      
      <div class="hidden-md hidden-lg hidden-sm">
        <%= render 'xs_percentages' %>
      </div>
      
    </div>
  </div>
  <div class="scroll-stop-prospecting scroll-arrow">
    <img src="<%= asset_path('landing_page/scroll-arrow.png') %>" alt="" />
  </div>
</div>

<div class="fortune-5000-companies">
  <h1 class="text-center questrial-font">Quickly Penetrate The Fortune 1000 Companies</h1>
  <h4 class="text-center railway-font squeeze-text">Leverage your network to navigate and penetrate companies. Gain insights on key stakeholders, major initiatives, RFPs and sales approaches</h4>
  <div class="landing-page-company-logos text-center">
    <ul class="list-inline hidden-xs">
      <li><img src="<%= asset_path("landing_page/apple_logo.png") %>" alt="" id="apple-logo" /></li>
      <li><img src="<%= asset_path("landing_page/walgreens_logo.png") %>" alt="" id="apple-logo" /></li>
      <li><img src="<%= asset_path("landing_page/samsung_logo.png") %>" alt="" id="apple-logo" /></li>
      <li><img src="<%= asset_path("landing_page/linked_in_logo.png") %>" alt="" id="apple-logo" /></li>
      <li><img src="<%= asset_path("landing_page/pepsi_logo.png") %>" alt="" id="apple-logo" /></li>
    </ul>
  </div>
  
  <div class="hidden-lg hidden-md hidden-sm text-center vertical-company-logos">
    <ul class="list-unstyled">
      <li><img src="<%= asset_path("landing_page/apple_logo.png") %>" alt="" id="apple-logo" /></li>
      <li><img src="<%= asset_path("landing_page/walgreens_logo.png") %>" alt="" id="apple-logo" /></li>
      <li><img src="<%= asset_path("landing_page/samsung_logo.png") %>" alt="" id="apple-logo" /></li>
      <li><img src="<%= asset_path("landing_page/linked_in_logo.png") %>" alt="" id="apple-logo" /></li>
      <li><img src="<%= asset_path("landing_page/pepsi_logo.png") %>" alt="" id="apple-logo" /></li>
    </ul>
  </div>
  
  <img src="<%= asset_path("landing_page/us_map.png") %>" class="us-background us-background-sm us-background-xs" alt="" id="apple-logo" />
  <div class="scroll-fortune-5000 scroll-arrow">
    <img src="<%= asset_path('landing_page/scroll-arrow.png') %>" alt="" />
  </div>
</div>

<div class="personal-networking-assistant">
  <h1 class="text-center questrial-font">Meet Your Personal Social Networking Assistant</h1>
  <h4 class="text-center railway-font">We automatically introduce you to peers who can help you grow your sales</h4>
  <div class="row">
    <div class="col-lg-offset-1 col-lg-5 col-md-offset-1 col-md-5 hidden-sm hidden-xs">
      <img class="col-lg-12 col-md-12" src="<%= asset_path('landing_page/magnifying_glass.png') %>" alt="" />
    </div>
    <div class="col-lg-5 hidden-sm hidden-xs col-md-5">
      <ul class="list-unstyled railway-font assistant-list">
        <li> <i class="fa fa-arrow-circle-right"></i>Easily find members linked to your target companies and departments.</li>
        <li> <i class="fa fa-arrow-circle-right"></i>Member introductions are based on mutually beneficial account linkages to connect you to the most relevant members.</li>
        <li> <i class="fa fa-arrow-circle-right"></i>Gain access to rich insights, initiatives, RFPs, and contact information.</li>
        <li> <i class="fa fa-arrow-circle-right"></i>Receive valuable coaching from members on sales strategy and approach.</li>
        <!-- <li> <i class="fa fa-arrow-circle-right"></i>Accelerate sales process with </li> -->
      </ul>
    </div>
    <div class="hidden-lg hidden-md">
      <div class="text-center">
        <img class="" src="<%= asset_path('landing_page/magnifying_glass.png') %>" alt="" width="400"/>
      </div>
      <ul class="list-unstyled col-md-6 col-xs-offset-2 railway-font assistant-list">
        <li> <i class="fa fa-arrow-circle-right"></i>Easily find members linked to your target companies and departments </li>
        <li> <i class="fa fa-arrow-circle-right"></i>Member introductions are based on mutual beneficial account linkages to connect you to the most relevant members.</li>
        <li> <i class="fa fa-arrow-circle-right"></i>Gain visibility to rich insights, initiatives, RFPs, and contact information.</li>
        <li> <i class="fa fa-arrow-circle-right"></i>Receive valuable coaching from members on sales strategy and approach.</li>
      </ul>
    </div>
  </div>
  <div class="scroll-networking-assistant scroll-arrow">
    <img src="<%= asset_path('landing_page/scroll-arrow.png') %>" alt="" />
  </div>
</div>

<div class="enterprise-deal">
  <div class="enterprise-deal-overlay text-center">
    <h1 class="questrial-font">Proven Approach</h1>
    <h2 class="questrial-font">I sold a $2.8 million enterprise deal.</h2>
    <h4 class="railway-font">I was prospecting into a target account for 6 months with little success. I connected with a peer who introduced me to a key stakeholder within the account and I was able to close a deal in 8 months. It works!</h4>
    <img src="<%= asset_path("landing_page/front_profile_logo.png") %>" alt="" />
    <p class="railway-font"> <i>Account Director, Market Services Company</i> </p>
    <div class="scroll-enterprise-deal">
      <img src="<%= asset_path('landing_page/scroll-arrow.png') %>" alt="" />
    </div>
  </div>
</div>

<div class="on-mission">
  <div class="text-center">
    <img src="<%= asset_path('logo-vertical.png') %>" alt="" />
    <h4 class="railway-font">We're on a mission to make your networking easier, more relavant and productive.</h4>
    <h1 class="questrial-font">Request Your Membership Today!</h1>
  </div>
  <a href="<%= user_omniauth_authorize_path(:linkedin) %>" class="btn railway-font main-request-button">Request Membership</a>
</div>

<footer id="front-footer">
  <div class="text-center footer-icons">

    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-twitter black-icon fa-stack-1x"></i>
    </span>
    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-facebook black-icon fa-stack-1x"></i>
    </span>
    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-linkedin black-icon fa-stack-1x"></i>
    </span>

  </div>
  <div class="text-center copyright">
    <p class="railway-font">&copy Peer Nation <%= Date.today.year %>. All rights reserved.</p>
    <ul class="list-inline">
      <li><a href="">Terms of Use</a></li>
      <li><a href="">Privacy Policy</a></li>
    </ul>
  </div>

</footer>