config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: 'admin/sessions', registrations: 'admin/registrations'}
  devise_scope :admin do
    get 'delta', to: 'admin/sessions#delta'
    get 'admins/sign_in', to: 'admin/sessions#delta'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users"}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  root 'welcome#index'
  get '/ref/:referrer' => 'welcome#index'

  # get '/portfolio/new' => 'portfolio_accounts#new'
  # post '/portfolio' => 'portfolio_accounts#create'
  resources :portfolio, controller: 'portfolio_accounts'
  get '/target/new' => 'target_accounts#new'
  post '/target' => 'target_accounts#create'

  resources :companies
  get '/profile' => 'users#profile'
  put '/profile' => 'users#update'
  patch '/profile' => 'users#update'
  get '/profile/new' => 'users#new_profile'
  post '/profile' => 'users#create_profile'
  patch '/submit' => 'users#submit_application'
  get '/submitted' => 'users#submitted'
  get '/edit/password/:id' => 'users#edit_password', as: :edit_password
  patch '/edit/password/:id' => 'users#update_password', as: :update_password

  resources :members, only: [:index, :show, :update]

  resources :connections

  resources :requests, only: [:index, :create]
  resources :comments
  resources :member_requests, only: [:index, :create]
  resources :app_images, only: [:new, :create]

  namespace :admin do
    resources :applications, only: [:index, :show, :update]
    resources :members, only: [:index, :show, :new, :create]
    resources :member_requests, only: [:index, :destroy]
    resources :industries, only: [:new, :create]
    resources :departments, only: [:new, :create]
    get '/new_requests' => 'members#new_requests'
    get '/unapproved' => 'members#unapproved'
    get '/rejected' => 'members#rejected'
    get '/current' => 'members#current'
    get '/new_companies' => 'companies#index'
    put '/members/suspend_member/:id' => 'members#suspend_member', as: :suspend_member
    patch '/members/suspend_member/:id' => 'members#suspend_member'
    put '/members/approve_member/:id' => 'members#approve_member', as: :approve_member
    patch '/members/approve_member/:id' => 'members#approve_member'
    put '/members/disapprove_member/:id' => 'members#disapprove_member', as: :disapprove_member
    put '/members/disapprove_member/:id' => 'members#disapprove_member'
  end

  resources :inbox, controller: 'conversations', except: [:edit, :show, :update]
  get '/inbox/sent_conversations' => 'conversations#sent'
  get '/inbox/archived_conversations' => 'conversations#archived'
  get '/inbox/trashed_conversations' => 'conversations#trashed'
  match '/inbox/archive_conversations' => 'conversations#archive', via: [:put, :patch]
  match '/inbox/trash_conversations' => 'conversations#trash', via: [:put, :patch]
  get '/inbox/message/:id' => 'conversations#show', as: :inbox_message
  get '/inbox/reply/:id' => 'conversations#reply', as: :inbox_reply
  post '/inbox/reply/:id' => 'messages#create'
  post '/send_message/:id' => 'conversations#send_message'
  resources :messages, only: [:create]
  resources :notifications, only: [:index, :destroy]

  namespace :api do
    namespace :v1 do
      resources :companies, only: [:index]
      get '/company_search' => 'companies#search'
      get '/async_search' => 'companies#async_search'
      get '/company_city_search' => 'companies#city_search'
      get '/member_search' => 'members#search'
      get 'member_city_search' => 'members#city_search'
      get '/company_members/:id' => 'members#company_members'
      get '/company_members_search/:id' => 'members#company_members_search'
      get '/peers' => 'members#peers_search'
      get '/company_peers/:id' => 'members#company_peers_search'
      resources :comments, only: [:index]
      resources :departments, only: [:index]
      resources :industries, only: [:index, :show]
      resources :users, only: [:index, :update]
      get '/user_industries' => 'users#industries'
      patch '/user_industries' => 'users#update_industries'
      get '/user_departments' => 'users#departments'
      patch '/user_departments' => 'users#update_departments'
      get '/current_user' => 'users#user'
      resources :portfolio_industries, only: [:index]
      resources :portfolio_departments, only: [:index]
      resources :conversations, only: [:index]
      get '/sent_conversations' => 'conversations#sent'
      get '/received_conversations' => 'conversations#received'
      get '/archived_conversations' => 'conversations#archived'
      get '/trashed_conversations' => 'conversations#trashed'
      match '/archive_conversations' => 'conversations#archive', via: [:put, :patch]
      match '/trash_conversations' => 'conversations#trash', via: [:put, :patch]
      resources :contact_levels, only: [:index]
      resources :connections, only: [:index, :create]
      resources :messages, only: [:show]
      get '/recipients' => 'connections#recipients'
      get '/recipients/:id' => 'connections#recipient'
      resources :notifications
      resources :referrals, only: [:create, :index]
      get '/avatars' => 'users#avatars'
      get '/states' => 'users#states'
    end
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :portfolio_accounts
  has_many :target_accounts
  has_many :company_industries
  has_many :company_departments
  has_many :portfolio_users, through: :portfolio_accounts, source: :user
  has_many :target_users, through: :target_accounts, source: :user
  has_many :portfolio_departments, dependent: :destroy
  has_many :target_departments, through: :target_accounts, source: :department
  has_many :portfolio_industries, through: :portfolio_accounts, source: :industry
  has_many :target_industries, through: :target_accounts, source: :industry
  has_many :comp_industries, through: :company_industries, source: :industry
  has_many :comp_departments, through: :company_departments, source: :department
  has_many :comments, :as => :commentable, :dependent => :destroy
  mount_uploader :logo, CompanyLogoUploader
  validates :city, presence: true
  validates :state, presence: true
  validates :name, presence: true

  scope :by_name, lambda { |name| where(name: name) }
  scope :by_city, lambda { |cities| where(city: cities) }

  def self.by_industry(ids)
    Company.joins(:comp_industries).where(company_industries: {industry_id: ids})
  end

  def contacts(user)
    all_contacts = portfolio_accounts.select {|account| user.id == account.user_id}.map {|account| account.contact_levels}
    all_contacts.join(",")
  end

  def image_size
    image_ratio = width.to_f / height.to_f
    return "square" if image_ratio < 1.5
    return "medium" if image_ratio < 2.0
    return "rectangle" if image_ratio > 2.0
  end

end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_filter :authorize_admin
  layout 'admin_dashboard'
  
  def index
    @companies = Company.where(created_at: 2.weeks.ago...Date.tomorrow)
  end
end

app/controllers/api/v1/companies_controller.rb
module Api
  module V1
    class CompaniesController < ApplicationController
      skip_before_filter :authenticate_user_or_admin
      def index
        @companies = Company.order('num_of_users desc nulls last')
        @companies = @companies.by_name(params["name"]) if params[:name]
      end

      def search
        industry_ids = params[:industry_ids].gsub("[", "").gsub("]", "").split(",")
        cities = params[:cities].gsub("[", "").gsub("]", "").split(",")
        companies = Company.order(num_of_users: :asc)
        companies = companies.by_industry(industry_ids) if !industry_ids.empty?
        companies = companies.by_city(cities) if !cities.empty?
        companies = companies.distinct

        render json: companies.to_json
      end

      def async_search
        companies = Company.where("lower(name) LIKE ?", "%#{params[:companies].downcase}%").limit(10)
        render json: companies.to_json
      end

      def city_search
        cities = Company.where("lower(city) LIKE?", "%#{params[:city].downcase}%").limit(10).map(&:city).uniq
        render json: cities.to_json
      end

    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user_or_admin, :approved_user, except: [:index]
  before_filter :authorize_admin, only: [:edit]
  before_filter :layout_landing_page

  def index
  end

  def new
    @company = Company.new
  end

  def show
    @company = Company.find(params[:id])
    @comments = @company.comments
    @comments = @comments.by_type(params[:type]) if params[:type].present?
    @comments = @comments.by_begin_date(params[:from]) if params[:from].present?
    @comments = @comments.by_end_date(params[:to]) if params[:to].present?
    @comments = Comment.by_contact if params[:comment_type] == "contact"
    @comments = Comment.by_question if params[:comment_type] == "question"
    @comments = Comment.by_comment if params[:comment_type] == "comment"
    params[:keywords] ||= ""
    @comments = Comment.by_keyword(params[:keywords]) if !params[:keywords].empty?
  end

  def create
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    redirect_to company_path(@company.id)
  end

  def layout_landing_page
    if !user_signed_in? && !admin_signed_in?
      self.class.layout 'companies'
    end
  end
  
  def company_params
    params.require(:company).permit(:logo, :width, :height)
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_target_alerts.html.erb
<div class="alert alert-success" ng-if="targetAdded">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <p>{{targetAdded}}</p>
</div>

app/views/companies/_target_form.html.erb
  <div class="alert alert-success" ng-if="targetAdded">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p>{{targetAdded}}</p>
  </div>
  <div class="alert alert-danger" ng-if="targetNotAdded">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <ul class="list-unstyled" ng-repeat="error in targetNotAdded">
      <li>{{error}}</li>
    </ul>
  </div>

  <div class="row" style="">
    <div class="col-lg-6">
      <label class="control-label" for="department">Department</label>
      <select class="form-control my-select" multiple="multiple" ng-model="target_account.department_ids">
        <% Department.all.order(name: :asc).each do |dep| %>
          <option value="<%= dep.id %>"><%= dep.name %></option>
        <% end %>
      </select>
    </div>
    <div class="col-lg-6">
      <label class="control-label" for="contact_levels">Contact Levels</label>
      <select class="form-control my-select" multiple="multiple" ng-model="target_account.contact_level_ids">
        <% ContactLevel.all.each do |contact| %>
        <option value="<%= contact.id %>"><%= contact.name %></option>
        <% end %>
      </select>
      <input value="true" type="hidden" name="portfolio_account[portfolio]" id="portfolio_account_portfolio">
      <input type="hidden" ng-model="target_account.company">
    </div>
  </div>

<div class="modal-footer" style="">
  <a href="#" class="pull-left" ng-click="cancel()">CANCEL</a>
  <button type="button" ng-click="updateTargetCompany(target_account)" class="create-target-button">Create</button>
</div>

<script type="text/javascript">
  $(document).ready(function () {
    $('.my-select').SumoSelect({placeholder: 'Select options from below'});
  });
</script>

app/views/companies/edit.html.erb
<%= form_for @company do |f| %>
  <%= f.text_field :name %>
  <%= f.file_field :logo %>
  <%= f.label :width %>
  <%= f.text_field :width %>
  <%= f.label :height %>
  <%= f.text_field :height %>
  <%= f.submit %>
<% end %>

app/views/companies/index.html.erb
<%# stylesheet_link_tag 'select-multiple' %>
<%= render 'layouts/alerts' %>

<div id="bottom-of-page">
  <div class="row">
    <div ng-controller="CompaniesController">
      <script type="text/ng-template" id="targetForm.html">
        <%= render 'target_form' %>
      </script>
      <div class="col-lg-2">
        <h4 class="color-909090">Refine search</h4>
        <div class="company-page-header-padding">
          <div class="filter-header">
            <h5 class="header-232426">INDUSTRIES</h5>
          </div>
          <div class="industries-list">
            <ul class="list-unstyled" ng-cloak ng-repeat="industry in industries track by industry.id">
              <li>
                <input class="my-checkbox" ng-disabled="inputsDisabled" ng-change="searchByIndustry(industry)" ng-model="industry.checked" ng-value="industry.name" type="checkbox"> {{industry.name}}
              </li>
            </ul>
          </div>
          <div class="filter-header">
            <h5 class="header-232426">COMPANY LOCATION</h5>
          </div>
          <div class="">
            <input type="text" ng-disabled="inputsDisabled" placeholder="City, State" name="name" ng-model="locationSelected" id="location-search-form" typeahead-loading='loadingCities' typeahead-select-on-blur="true" typeahead-no-results="noResults" uib-typeahead="location for location in getLocation($viewValue) | limitTo:8" typeahead-on-select="searchByCity($item)" autocomplete="off" >
            <i ng-show="loadingCities" class="fa fa-spinner"></i>
            <div ng-show="noResults">
              <p class="fa fa-times" ng-click="clearCitySearch()">No Results Found</i></p>
            </div>
            <p ng-repeat="city in cities track by $index" class="pull-left" id="searched-cities" ng-cloak>{{city}} <i class="fa fa-times" ng-click="unselectCity(city)"></i></p>
          </div>
          <div class="col-lg-12 row">
            <button type="button" name="button" class="search-button" style="margin-top: 40px;" ng-click="clearSearch()">clear search</button>
          </div>
        </div>
      </div>
      <div class="col-lg-10" ng-cloak>
        <h4 class="ACADAF" ng-if="companies.length < numAllCompanies"><span class="header-232426">{{companies.length}} Companies</span> match your search</h4>
        <h4 class="ACADAF" ng-if="companies.length === numAllCompanies"><span class="header-232426">{{companies.length}} Companies</span></h4>
        <div class="row company-page-header-padding">
          <div ng-repeat="company in companies | limitTo: companyLimit track by company.id">
            <div class="col-lg-3">
              <i class="fa fa-bullseye bullseye" ng-click="addCompany(company, 'lg')"></i>
              <a ng-href="/companies/{{company.id}}" id="thumbnail-link">
                <div class="thumbnail text-center">
                  <div ng-class="{'logo-rectangle-class': isRectangleImage(company.width, company.height), 'logo-square-class': isSquareImage(company.width, company.height), 'logo-medium-class': isMediumImage(company.width, company.height)}">
                    <img ng-src="{{company.logo.logo.url}}" width="100px" alt="" />
                  </div>
                  <div class="position-company-info">
                    <div class="thumbnail-border"></div>
                    <h5>{{company.name}}</h5>
                    <h6>{{company.city + ", " + company.state}}</h6>
                  </div>
                  <ul class="list-inline list-unstyled bottom-thumbnail">
                    <li><i class="glyphicon glyphicon-user"></i>{{company.num_of_users}}</li>
                    <li><i class="fa fa-comments"></i>{{company.num_of_comments}}</li>
                  </ul>
                </div>
              </a>

            </div>
          </div>
        </div>
        <button class="btn btn-default" ng-show="companies.length > 20 && companyLimit < companies.length" ng-click="loadMore()" ng-cloak>Load more</button>
      </div>
    </div>
  </div>
</div>

<%# javascript_include_tag 'select-multiple' %>

app/views/companies/new.html.erb
<%= form_for @company do |f| %>
  <%= f.text_field :name %>
  <%= f.file_field :logo %>
<% end %>

app/views/companies/show.html.erb
<%= stylesheet_link_tag 'select-multiple' %>
<div id="company-id" data-url="<%= params[:id] %>"></div>
<div id="show-posts" data-url="<%= params[:post] %>"></div>
<div ng-controller="CommentsController">
  <div class="row" ng-cloak>

    <div class="col-lg-12">
      <%= render 'target_alerts' %>
    </div>
    
    <script type="text/ng-template" id="targetForm.html">
      <%= render 'target_form' %>
    </script>
    
    <% if current_admin %>
      <p><%= link_to 'Edit', edit_company_path(@company.id) %></p>
    <% end %>
    <p> <strong><%= @company.portfolio_users.length %> members</strong> have this company in their Portfolio </p>

    <div class="col-lg-2">
      <div class="row thumbnail text-center">
        <i class="fa fa-bullseye bullseye-company-show" ng-click="open('lg')"></i>
        <div class="logo-<%= @company.image_size %>-class">
          <img src="<%= @company.logo.url %>" alt="" />
        </div>
        <div style="margin-top: 20px;">
          <div class="thumbnail-border"></div>
        </div>
        <h5><%= @company.name %></h5>
        <h6><%= @company.city + ", " + @company.state %></h6>
        <ul class="list-inline list-unstyled bottom-thumbnail">
          <li><i class="glyphicon glyphicon-user"></i><%= @company.num_of_users %></li>
          <li><i class="fa fa-comments"></i><%= @company.num_of_comments %></li>
        </ul>
      </div>

      <div class="row" ng-show="showPosts">
        <%= render 'comments/comment_search' %>
      </div>

      <div class="row" ng-show="showMembers">
        <%= render 'members/member_search' %>
      </div>

    </div>

    <div class="col-lg-10">
      <div class="row">
        <div class="col-lg-12">
          <ul class="pull-left portfolio-tabs list-unstyled">
            <li ng-class="{'active-tab': showMembers, 'inactive-tab': !showMembers}" ng-click="showTab('members')"><a href="#"><i class="glyphicon glyphicon-user" ng-cloak></i> Members ({{members.length}})</a></li>
            <li ng-class="{'active-tab': showPosts, 'inactive-tab': !showPosts}" ng-click="showTab('posts')"><a href="#"><i class="fa fa-comments"></i> Posts ({{posts.length}})</a></li>
          </ul>
        </div>
      </div>

      <div ng-show="showMembers">
        <div class="col-lg-12">
          <%= render 'members/members' %>
        </div>
      </div>

      <div ng-show="showPosts">
        <div class="alert alert-danger" ng-if="targetNotAdded">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <ul class="list-unstyled" ng-repeat="error in targetNotAdded">
            <li>{{error}}</li>
          </ul>
        </div>
        <%= render 'comments/form' if current_user || current_admin %>

        <div class="col-lg-12">
          
          <!-- This is where the angular comment comes in, just the once right after they post -->
          <% if current_user || current_admin %>
          <div ng-if="newComment" ng-cloak class="row ancestor-section">
            <div class="col-lg-1">
              <img src="<%= current_user.linkedin_photo if current_user %>" width="50" alt="" />
            </div>
            <div class="col-lg-10">
              <div class="row">
                <div class="col-lg-12">
                  <h5 class="pull-left"><%= current_user.full_name if current_user %></h5>
                  <p><i class="pull-right">{{comment.created_at | date:'MMM dd, yyyy'}}</i></p>
                </div>
                <div class="col-lg-12">
                  <p>{{comment.content}}</p>
                </div>
              </div>
            </div>
          </div>
          <%= nested_comments(@comments) %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

<%= javascript_include_tag 'select-multiple' %>