config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: 'admin/sessions', registrations: 'admin/registrations'}
  devise_scope :admin do
    get 'delta', to: 'admin/sessions#delta'
    get 'admins/sign_in', to: 'admin/sessions#delta'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users"}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  root 'welcome#index'
  get '/ref/:referrer' => 'welcome#index'

  # get '/portfolio/new' => 'portfolio_accounts#new'
  # post '/portfolio' => 'portfolio_accounts#create'
  resources :portfolio, controller: 'portfolio_accounts'
  get '/target/new' => 'target_accounts#new'
  post '/target' => 'target_accounts#create'

  resources :companies
  get '/profile' => 'users#profile'
  put '/profile' => 'users#update'
  patch '/profile' => 'users#update'
  get '/profile/new' => 'users#new_profile'
  post '/profile' => 'users#create_profile'
  patch '/submit' => 'users#submit_application'
  get '/submitted' => 'users#submitted'
  get '/edit/password/:id' => 'users#edit_password', as: :edit_password
  patch '/edit/password/:id' => 'users#update_password', as: :update_password

  resources :members, only: [:index, :show, :update]

  resources :connections

  resources :requests, only: [:index, :create]
  resources :comments
  resources :member_requests, only: [:index, :create]
  resources :app_images, only: [:new, :create]

  namespace :admin do
    resources :applications, only: [:index, :show, :update]
    resources :members, only: [:index, :show, :new, :create]
    resources :member_requests, only: [:index, :destroy]
    resources :industries, only: [:new, :create]
    resources :departments, only: [:new, :create]
    get '/new_requests' => 'members#new_requests'
    get '/unapproved' => 'members#unapproved'
    get '/rejected' => 'members#rejected'
    get '/current' => 'members#current'
    get '/new_companies' => 'companies#index'
    put '/members/suspend_member/:id' => 'members#suspend_member', as: :suspend_member
    patch '/members/suspend_member/:id' => 'members#suspend_member'
    put '/members/approve_member/:id' => 'members#approve_member', as: :approve_member
    patch '/members/approve_member/:id' => 'members#approve_member'
    put '/members/disapprove_member/:id' => 'members#disapprove_member', as: :disapprove_member
    put '/members/disapprove_member/:id' => 'members#disapprove_member'
  end

  resources :inbox, controller: 'conversations', except: [:edit, :show, :update]
  get '/inbox/sent_conversations' => 'conversations#sent'
  get '/inbox/archived_conversations' => 'conversations#archived'
  get '/inbox/trashed_conversations' => 'conversations#trashed'
  match '/inbox/archive_conversations' => 'conversations#archive', via: [:put, :patch]
  match '/inbox/trash_conversations' => 'conversations#trash', via: [:put, :patch]
  get '/inbox/message/:id' => 'conversations#show', as: :inbox_message
  get '/inbox/reply/:id' => 'conversations#reply', as: :inbox_reply
  post '/inbox/reply/:id' => 'messages#create'
  post '/send_message/:id' => 'conversations#send_message'
  resources :messages, only: [:create]
  resources :notifications, only: [:index, :destroy]

  namespace :api do
    namespace :v1 do
      resources :companies, only: [:index]
      get '/company_search' => 'companies#search'
      get '/async_search' => 'companies#async_search'
      get '/company_city_search' => 'companies#city_search'
      get '/member_search' => 'members#search'
      get 'member_city_search' => 'members#city_search'
      get '/company_members/:id' => 'members#company_members'
      get '/company_members_search/:id' => 'members#company_members_search'
      get '/peers' => 'members#peers_search'
      get '/company_peers/:id' => 'members#company_peers_search'
      resources :comments, only: [:index]
      resources :departments, only: [:index]
      resources :industries, only: [:index, :show]
      resources :users, only: [:index, :update]
      get '/user_industries' => 'users#industries'
      patch '/user_industries' => 'users#update_industries'
      get '/user_departments' => 'users#departments'
      patch '/user_departments' => 'users#update_departments'
      get '/current_user' => 'users#user'
      resources :portfolio_industries, only: [:index]
      resources :portfolio_departments, only: [:index]
      resources :conversations, only: [:index]
      get '/sent_conversations' => 'conversations#sent'
      get '/received_conversations' => 'conversations#received'
      get '/archived_conversations' => 'conversations#archived'
      get '/trashed_conversations' => 'conversations#trashed'
      match '/archive_conversations' => 'conversations#archive', via: [:put, :patch]
      match '/trash_conversations' => 'conversations#trash', via: [:put, :patch]
      resources :contact_levels, only: [:index]
      resources :connections, only: [:index, :create]
      resources :messages, only: [:show]
      get '/recipients' => 'connections#recipients'
      get '/recipients/:id' => 'connections#recipient'
      resources :notifications
      resources :referrals, only: [:create, :index]
      get '/avatars' => 'users#avatars'
      get '/states' => 'users#states'
    end
  end
end

app/models/portfolio_account.rb
class PortfolioAccount < ActiveRecord::Base
  has_many :portfolio_departments, dependent: :destroy
  has_many :departments, through: :portfolio_departments
  has_many :contact_levels, through: :portfolio_departments
  belongs_to :company
  belongs_to :user
  belongs_to :industry
  validates :company_id, presence: true, uniqueness: {scope: :user_id, message: 'has already been added to your portfolio.'}
  validates :user_id, presence: true
end

app/controllers/portfolio_accounts_controller.rb
class PortfolioAccountsController < ApplicationController
  before_filter :redirect_if_admin
  def new
    @portfolio = PortfolioAccount.new
    @states = YAML.load(File.read(File.expand_path("#{Rails.root}/config/states.yml", __FILE__)))
  end

  def create
    if params_nil? && (params[:next] || params[:profile])
      route_to = {next: true} if params[:next]
      route_to = {profile: true} if params[:profile]
      render json: route_to.to_json
    else
      company = FindCompany.new(company_params).create_portfolio
      if company.errors.empty?
        portfolio = PortfolioAccount.new(user_id: current_user.id, company_id: company.id)
        if portfolio.save
          build_associations(portfolio)
          company.num_of_users ? company.num_of_users += 1 : company.num_of_users = 1
          company.save
          if params[:next]
            flash[:notice] = "#{current_user.portfolio_companies.size} Companies added to your account"
            render json: {next: true}.to_json
          elsif params[:profile]
            flash[:notice] = "#{current_user.portfolio_companies.size} Companies added to your account"
            render json: {profile: true}.to_json
          else
            render json: "#{current_user.portfolio_companies.size} Companies added to your account".to_json
          end
        else
          render json: portfolio.errors.full_messages.to_json, status: :unprocessable_entity
        end
      else
        render json: company.errors.full_messages.to_json, status: :unprocessable_entity
      end
    end
  end

  def edit
    @portfolio = PortfolioAccount.find(params[:id])
  end

  def update
    department_ids = params[:portfolio_account][:departments][:department_ids].reject{|id| id.empty?}.map{|id| id.to_i}
    contact_level_ids = params[:portfolio_account][:contact_levels][:contact_level_ids].reject{|id| id.empty?}.map{|id| id.to_i}
    @portfolio = PortfolioAccount.find(params[:id])
    if department_ids.empty?
      flash.now[:danger] = "Please select at least one department"
      render :edit
    elsif contact_level_ids.empty?
      flash.now[:danger] = "Please select at least one contact"
      render :edit
    else
      update_associations(department_ids, contact_level_ids, @portfolio)
      flash[:success] = "Profile updated"
        redirect_to profile_path
    end
  end

  def destroy
    portfolio = PortfolioAccount.find(params[:id])
    company = portfolio.company
    company.update(num_of_users: company.num_of_users - 1)
    if portfolio.destroy
      flash[:success] = "Portfolio destroyed"
    else
      flash[:warning] = "Something went wrong, please try again"
    end
    redirect_to profile_path
  end

  private

  def company_params
    {
      id: params[:company_id],
      name: params[:company],
      state: params[:state],
      city: params[:city],
      department_ids: params[:department_ids],
      contact_level_ids: params[:contact_level_ids],
      industry_ids: params[:industry_ids],
      new_company: params[:new_company]
    }
  end

  def params_nil?
    (params[:company].nil? || params[:company].empty?) && params[:department_ids].nil? && params[:industry_ids].nil? && params[:city].nil? && params[:state].nil? && params[:contact_level_ids].nil?
  end

  def build_associations(portfolio)
    build_departments(portfolio)
    build_contact_levels(portfolio)
  end

  def update_associations(department_ids, contact_level_ids, portfolio)
    update_departments(department_ids, portfolio)
    update_contact_levels(contact_level_ids, portfolio)
  end

  def build_departments(portfolio)
    params[:department_ids].each do |id|
      PortfolioDepartment.create(user_id: current_user.id, department_id: id, portfolio_account_id: portfolio.id)
    end
  end

  def build_contact_levels(portfolio)
    params[:contact_level_ids].each do |id|
      PortfolioDepartment.create(user_id: current_user.id, contact_level_id: id, portfolio_account_id: portfolio.id)
    end
  end

  def update_departments(ids, portfolio)
    portfolio_ids = portfolio.departments.map(&:id)
    destroy_ids = portfolio_ids - ids
    destroy_ids.each do |id|
      PortfolioDepartment.find_by(user_id: current_user.id, department_id: id, portfolio_account_id: portfolio.id).destroy
    end
    create_ids = ids - portfolio_ids
    create_ids.each do |id|
      PortfolioDepartment.create(user_id: current_user.id, department_id: id, portfolio_account_id: portfolio.id)
    end
  end

  def update_contact_levels(ids, portfolio)
    portfolio_ids = portfolio.contact_levels.map(&:id)
    destroy_ids = portfolio_ids - ids
    destroy_ids.each do |id|
      PortfolioDepartment.find_by(user_id: current_user.id, contact_level_id: id, portfolio_account_id: portfolio.id).destroy
    end
    create_ids = ids - portfolio_ids
    create_ids.each do |id|
      PortfolioDepartment.create(user_id: current_user.id, contact_level_id: id, portfolio_account_id: portfolio.id)
    end
  end

  def portfolio_params
    params.require(:portfolio_account).permit(:company_id, department_ids: [], contact_level_ids: [])
  end

end

app/views/portfolio_accounts/edit.html.erb
<%= stylesheet_link_tag 'select-multiple' %>
<div class="row">
  <div class="col-lg-10 col-lg-offset-1" ng-controller="MainSearchController">
    <%= render 'layouts/alerts' %>
    <ul class="list-unstyled col-lg-12 list-inline sign-up-form-header">
      <li><h4>Edit Your Portfolio</h4></li>
    </ul>
    <div class="col-lg-12">
      <div class="sign-up-form-border"></div>
    </div>
    <div class="text-center">
      <img src="<%= @portfolio.company.logo %>" width="100px" alt="" />
    </div>
    <div class="col-lg-12 sign-up-form">
      <%= form_for(@portfolio, url: portfolio_path(@portfolio)) do |f| %>
        <h4><%= @portfolio.company.name %></h4>
        
        <div class="row">
          <div class="col-lg-6">
            <%= f.fields_for :departments do |dep| %>
              <%= dep.label :department_id, "Department", class: 'my-select-label' %>
              <%= dep.select :department_ids, options_from_collection_for_select(Department.all, :id, :name, @portfolio.departments.map(&:id)), {}, {class: 'my-select hide', multiple: true} %>
            <% end %>
          </div>
          <div class="col-lg-6">
            <%= f.fields_for :contact_levels do |contact| %>
              <%= contact.label :contact_level_id, "Contact Levels", class: 'my-select-label' %>
              <%= contact.select :contact_level_ids, options_from_collection_for_select(ContactLevel.all, :id, :name, @portfolio.contact_levels.map(&:id)), {}, {class: 'my-select hide', multiple: true} %>
            <% end %>
          </div>
        </div>
        <div class="sign-up-form-border su-form-border-margin"></div>
      <div class="text-center final-button sign-up-form-button">
        <%= f.submit "Update Company" %>
      </div>
        
      <% end %>
    </div>
  </div>
  
</div>

<%= javascript_include_tag 'select-multiple' %>
<script type="text/javascript">
$(document).ready(function () {
  $('.my-select').SumoSelect({placeholder: 'Select options from below'});
 });
</script>

app/views/portfolio_accounts/new.html.erb
<%= stylesheet_link_tag 'select-multiple' %>
<div class="cubed" ng-controller="PortfoliosController">

  <div class="col-lg-10 col-lg-offset-1" ng-controller="MainSearchController">
    <%= render 'layouts/alerts' %>
    <div class="alert alert-success" ng-cloak ng-if="saved">
      <button type="button" class="close" aria-label="Close"><span ng-click="hideAlert()" aria-hidden="true">&times;</span></button>
      <ul class="list-unstyled">
        <li>{{saved}}</li>
      </ul>
    </div>
    <div class="alert alert-danger" ng-cloak ng-if="hasErrors">
      <button type="button" class="close" aria-label="Close"><span ng-click="hideAlert()" aria-hidden="true">&times;</span></button>
      <ul class="list-unstyled">
        <li ng-repeat="error in errors track by $index">{{error}}</li>
      </ul>
    </div>

    <h2 class="text-center white-text">Add companies to your portfolio</h2>
    <h4 class="text-center white-text">List companies you have relationships with and can assist members with key insights</h4>

    <div class="text-center">
      <img ng-src="{{logo}}" ng-if="logo" width="100px" alt="" />
    </div>

    <div class="center sign-up-form">
      <form name="portfolioForm" class="form-horizontal" style="margin-top: 20px;">

        <div class="form-group">
          <input class="form-control" type="text" ng-model="portfolio_account.company" typeahead-select-on-blur="true" typeahead-on-select="setCompanyInfo($item)" typeahead-loading = 'loadingCompanies' uib-typeahead = 'company.name for company in getCompanies($viewValue)' typeahead-no-results = "noResults" class="portfolio-input my-input" placeholder="What company does your connection work with" autocomplete="off">
        </div>

        <div class="form-group">
          <select class="form-control my-select2" id="department-select" multiple="multiple" ng-model="portfolio_account.department_ids">
            <% Department.all.order(name: :asc).each do |dep| %>
              <option value="<%= dep.id %>"><%= dep.name %></option>
            <% end %>
          </select>
        </div>

        <div class="form-group">
          <select class="form-control" id="contact-select" multiple="multiple" ng-model="portfolio_account.contact_level_ids">
            <% ContactLevel.all.each do |contact| %>
            <option value="<%= contact.id %>"><%= contact.name %></option>
            <% end %>
          </select>
        </div>

        <div class="text-center">
          <div>
            <a class="white-text" href="#" ng-click="updatePortfolio(portfolio_account)">Add More</a>
          </div>
          <div class="sign-up-form-button">
            <% if current_user.submitted %>
              <a href="#" ng-click="goToProfile(portfolio_account)" class="final-button">Profile</a>
            <% else %>
              <a href="#" ng-click="next(portfolio_account)" class="final-button">Next</a>
            <% end %>
          </div>
        </div>

      </form>
    </div>
  </div>
</div>

<%= javascript_include_tag 'select-multiple.min' %>

<script type="text/javascript">
  $(document).ready(function () {
    $('#department-select').SumoSelect({placeholder: 'Select departments that your contacts work in'});
    $('#contact-select').SumoSelect({placeholder: 'Select contact level'});
  });
</script>